# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 05:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtaar', models.CharField(blank=True, max_length=256, null=True)),
                ('aiml', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('lang', models.CharField(blank=True, max_length=64, null=True)),
                ('avail', models.CharField(choices=[('N', 'None'), ('U', 'Users'), ('E', 'Everyone')], default='A', max_length=1)),
                ('views', models.IntegerField(default=0)),
                ('chatlog', models.CharField(blank=True, max_length=256, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
