# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='desc',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
