# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0003_auto_20170808_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='aiml',
            new_name='rive',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='lang',
        ),
        migrations.AlterField(
            model_name='bot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
