# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0004_auto_20170809_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='rive',
        ),
        migrations.AddField(
            model_name='bot',
            name='brain',
            field=models.FileField(blank=True, null=True, upload_to='brain/'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='avtaar',
            field=models.ImageField(blank=True, null=True, upload_to='avtaar/'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='chatlog',
            field=models.FileField(blank=True, null=True, upload_to='log/'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='desc',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
