# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0005_auto_20170811_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='avtaar',
            field=models.ImageField(blank=True, null=True, upload_to='files/avtaar/'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='brain',
            field=models.FileField(blank=True, null=True, upload_to='files/brain/'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='chatlog',
            field=models.FileField(blank=True, null=True, upload_to='files/log/'),
        ),
    ]
