# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 06:07
from __future__ import unicode_literals

import botapp.helper.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0009_auto_20170813_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='avtaar',
            field=models.FileField(blank=True, null=True, upload_to=botapp.helper.helper.generate_filename),
        ),
        migrations.AlterField(
            model_name='bot',
            name='brain',
            field=models.FileField(blank=True, null=True, upload_to=botapp.helper.helper.generate_filename),
        ),
        migrations.AlterField(
            model_name='bot',
            name='chatlog',
            field=models.FileField(blank=True, null=True, upload_to=botapp.helper.helper.generate_filename),
        ),
    ]
