# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0010_auto_20170814_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='avail',
        ),
        migrations.AddField(
            model_name='bot',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
