# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-16 10:26
from __future__ import unicode_literals

import botapp.helper.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0012_auto_20170815_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='avtaar',
            field=models.FileField(default='D:\\Projects\\WEB\\myapp-makemybot\\media\\avtaar/bot_default.png', upload_to=botapp.helper.helper.generate_filename),
        ),
        migrations.AlterField(
            model_name='bot',
            name='brain',
            field=models.FileField(default='D:\\Projects\\WEB\\myapp-makemybot\\media\\avtaar/bot_default.png', upload_to=botapp.helper.helper.generate_filename),
        ),
        migrations.AlterField(
            model_name='bot',
            name='message',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='bot',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
