# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-16 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0014_auto_20170816_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(blank=True, default='Chatty', max_length=32, null=True),
        ),
    ]
