# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-16 13:46
from __future__ import unicode_literals

import botapp.helper.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0015_auto_20170816_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='avtaar',
            field=models.FileField(default='avtaar/avtaar_default.png', upload_to=botapp.helper.helper.generate_filename),
        ),
        migrations.AlterField(
            model_name='bot',
            name='brain',
            field=models.FileField(default='brain/brain_default.rive', upload_to=botapp.helper.helper.generate_filename),
        ),
        migrations.AlterField(
            model_name='bot',
            name='description',
            field=models.TextField(blank=True, default='', max_length=128),
        ),
    ]
